from abfold.preprocess.numbering import number_seq


def test():
    H_seq = 'QVQLVESGPGLVQPSQSLSITCTVSGFSLSTYGVHWVRQSPGKGLEWLGVIWSGGSTDYNAAFISRLSITKDNSKSQVFFKMNSLQPNDTAVYYCDRMRITTDWFAYWGQGTLVTVSAAKTTPPSVYPLAPGSAAQTNSMVTLGCLVKGYFPEPVTVTWNSGSLSSGVHTFPAVLQSDLYTLSSSVTVPSSTWPSETVTCNVAHPASSTKVDKKIVPR'
    L_seq = 'DVLMTQSPLSLPVSLGDQASISCRSSQTIVHSNGNTYLEWYLQKPGQSPKLLIYKVSNRFYGVPDRFSGSGSGTDFTLKISRVEAEDLGVYYCFQGSHVPYTFGGGTKLEIKRADAAPTVSIFPPSSEQLTSGGASVVCFLNNFYPKDINVKWKIDGSERQNGVLNSWTDQDSKDSTYSMSSTLTLTKDEYERHNSYTCEATHKTSTSPIVKSFNRNEC'
    input_seqs = [('H', H_seq), ('L', L_seq)]
    ret = number_seq(input_seqs)
    print(ret)


if __name__ == '__main__':
    test()
