from carbonmatrix.data.antibody.seq import make_ab_numbering
from carbonmatrix.data.antibody import antibody_constants


def main():
    # 7uot, heavy chain
    seq1 = 'DVQLQESGPSLVKPSQTLSLTCSVTGDSITSDYWSWIRKFPGNRLEYMGYVSYSGSTYYNPSLKSRISITRDTSKNQYYLDLNSVTTEDTATYYCANWDGDYWGQGTLVTVSAAKTTPPSVYPLAPGSAAQTNSMVTLGCLVKGYFPEPVTVTWNSGSLSSGVHTFPAVLQSDLYTLSSSVTVPSSPRPSETVTCNVAHPASSTKVDKKIVPRDC'
    seq1 = 'AEFGQGTLRESGPGLVRPSETLSLTCGVSGYSISSGYYWGWIRQPPGKGLEWIGNIYRSGSTYYNPSLKSRVTVSIDTSKNQFSLKLNSVTAADTAVYYCARSGIKVADDYYYEMDVWGQGTDDYSYAMDVWGQGTTVTVDEF'
    # 7uot, light chain
    seq2 = 'QAVLTQPASVSGSPGQSITISCTAANSDIGDFAFVSWYQQRPDKAPKLMVYEVSSRPSGVSNRFSGSKSGNTASLTISGLQAEDEADYYCTSYTSSSTFVFGTGTKVTV'
    seq2 = 'DIVLTQSPATLSVTPGNSVSLSCRASQSIGNNLHWYQQKSHESPRLLIKYASQSISGIPSRFSGSGSGTDFTLSINSVETEDFGMYFCQQSNSWPYTFGGGTKLEIKRADAAPTVSIFPPSSEQLTSGGASVVCFLNNFYPKDINVKWKIDGSERQNGVLNSWTDQDSKDSTYSMSSTLTLTKDEYERHNSYTCEATHKTSTSPIVKSFNRNEC'
    
    # ret = make_ab_numbering(seq1, allow=['H'])
    ret = make_ab_numbering(seq2, allow=['K', 'L'])
    
    print(ret)

if __name__ == '__main__':
    main()