make_esm_seq: {}
make_restype_atom_constants: {}
make_center_positions: {}
make_atom14_alt_gt_positions: {}
make_gt_frames: {}
make_torsion_angles: {}
make_pseudo_beta: {}
make_t: {}

make_gt_score:
  se3_conf:
    diffuse_rot: true
    diffuse_trans: true
    r3:
      min_b: 0.1
      max_b: 20.0
      coordinate_scaling: 0.1
    so3:
      num_omega: 1000
      num_sigma: 1000
      min_sigma: 0.1
      max_sigma: 1.5
      schedule: "logarithmic"
      igso3_density_data: "../carbon_data/igso3/igso3_density_data.npz"
