defaults:
  - model: immunefold
  - transforms: immunefold_inference

restore_model_ckpt: ./params/immunefold-ab.ckpt
restore_esm2_model: ./params/esm2_t36_3B_UR50D.pt

gpu: 0

batch_size: 4

type: ab

data_io: abag

fasta: ./data/6icc_H_L_A.fasta

ag: ./data/6icc_A_ag.pdb

contact_idx: 15

output_dir: ./pred/abag

verbose: 1
