defaults:
  - model: carbonfold
  - transforms: carbonfold_inference

restore_model_ckpt: ../abdata_2023/esm2/carbonfold0.ckpt
# restore_esm2_model: ../abdata_2023/esm2/esm2_t36_3B_UR50D.pt
restore_esm2_model: ../abdata_2023/trained_models/stage1/step_20000_lora_merged.ckpt

gpu: 3

batch_size: 1

data_type: ig

data_io: fasta
test_data: ../abdata_2023/benchmark/test_esmfold.fasta

output_dir: ../abdata_2023/benchmark/abfold2/stage1

verbose: 1
