defaults:
  - model: esmfold
  - transforms: esmfold_inference

restore_model_ckpt: /home/zhutian/Git_repo/carbonmatrix/studies/abfold/2024-07-27/checkpoints/ab_20000_lora_merged.ckpt
# restore_esm2_model: ../abdata_2023/esm2/esm2_t36_3B_UR50D.pt
restore_esm2_model: /home/zhutian/data/esm_ckpt/esm2_t36_3B_UR50D.pt

gpu: 0

batch_size: 10

mode: tcrfold

data_type: 'ig'

data_io: fasta

test_data: /home/zhutian/data/antibody/antigen_fasta/test_all.fasta

output_dir: /home/zhutian/Git_repo/carbonmatrix/pred/ag_diff

verbose: 1
