defaults:
  - model: esmfold
  - transforms: esmfold_inference

# restore_model_ckpt: /home/zhutian/data/abdata_2023/esm2/carbonfold2_base_from_esmfold.ckpt
restore_esm2_model: /home/zhutian/data/abdata_2023/esm2/esm2_t36_3B_UR50D.pt
restore_model_ckpt: /home/zhutian/Git_repo/studies/tcrfold/2024-05-06/checkpoints/step_1000.ckpt
# restore_model_ckpt: ../abdata_2023/esm2/carbonfold2_base_from_esmfold.ckpt
# restore_esm2_model: ../abdata_2023/esm2/esm2_t36_3B_UR50D.pt

gpu: 2

batch_size: 1

mode: tcrfold

data_type: 'ig'

data_io: fasta

test_data: /home/zhutian/data/tcr_data/test_ab.fasta

output_dir: /home/zhutian/Git_repo/carbonmatrix/pred/tcrfold_3000

verbose: 1
