defaults:
  - model: immunefold
  - transforms: immunefold_inference

restore_model_ckpt: ./params/immunefold-ab.ckpt
# restore_esm2_model: ../abdata_2023/esm2/esm2_t36_3B_UR50D.pt
restore_esm2_model: ./params/esm2_t36_3B_UR50D.pt

gpu: 0

batch_size: 4

mode: ImmuneFold

data_type: 'ig'

data_io: abag

fasta: /home/zhutian/Git_repo/ImmuneFold/data/6icc_H_L_A.fasta

ag: /home/zhutian/Git_repo/ImmuneFold/data/6icc_A_ag.pdb

contact_idx: 15

output_dir: /home/zhutian/Git_repo/ImmuneFold/pred/new_pred

verbose: 1
