defaults:
  - model: esmfold
  - transforms: esmfold_inference

restore_model_ckpt: /home/zhutian/Git_repo/carbonmatrix/studies/abfold/2024-07-18/step_7000_lora_merged.ckpt
# restore_esm2_model: ../abdata_2023/esm2/esm2_t36_3B_UR50D.pt
restore_esm2_model: /home/zhutian/data/esm_ckpt/esm2_t36_3B_UR50D.pt

gpu: 0

batch_size: 24

mode: esmfold

data_type: 'general'

data_io: fasta

test_data: /home/zhutian/data/imfold/test2024/nano/nano_test_combined_sep.fasta

output_dir: /home/zhutian/Git_repo/carbonmatrix/pred/nano/imfold_7000

verbose: 1
