defaults:
  - model: esmfold
  - transforms: esmfold_inference

restore_model_ckpt: /home/zhutian/Git_repo/carbonmatrix/ab_8000_lora_merged.ckpt
# restore_esm2_model: ../abdata_2023/esm2/esm2_t36_3B_UR50D.pt
restore_esm2_model: /home/zhutian/data/esm_ckpt/esm2_t36_3B_UR50D.pt

gpu: 0

batch_size: 6

data_type: ig
mode: tcrfold
data_io: fasta

test_data: /home/zhutian/Git_repo/carbonmatrix/pred/PD_1.fasta

output_dir: ./pred/PD-1/

verbose: 1
