defaults:
  - model: carbonfold_diffuser
  - transforms: diffuser_inference

# restore_model_ckpt: ../abdata_2023/esm2/carbonfold0.ckpt
restore_model_ckpt: ../carbon_data/trained_models/train_diffuser_fft_v2/step_15000.ckpt
restore_esm2_model: ../abdata_2023/esm2/esm2_t36_3B_UR50D.pt

gpu: 3

batch_size: 1

data_io: npz
test_name_idx:  ../casp15_data/name.list
test_data: /home/zhutian/data/CASP15_whole/npz

output_dir: ../studies/carbonfold/casp15/train_diffuser_fft_v2_step_15000/pred4

verbose: 1
