defaults:
  - model: carbonfold
  - transforms: carbonfold_inference

restore_model_ckpt: ../abdata_2023/esm2/carbonfold0.ckpt
restore_esm2_model: ../abdata_2023/esm2/esm2_t36_3B_UR50D.pt

gpu: 3

batch_size: 1

data_io: dir
test_name_idx:  /home/zhutian/data/CASP15_whole/name.idx
test_data: /home/zhutian/data/CASP15_whole/fasta

output_dir: ./studies/test0

verbose: 1
