defaults:
  - model: esmfold
  - transforms: esmfold_inference

restore_model_ckpt: /home/zhutian/Git_repo/carbonmatrix/studies/abfold/ab_10000_lora_merged.ckpt
# restore_esm2_model: ../abdata_2023/esm2/esm2_t36_3B_UR50D.pt
restore_esm2_model: /home/zhutian/data/esm_ckpt/esm2_t36_3B_UR50D.pt

gpu: 0

batch_size: 18

mode: tcrfold

data_type: 'ig'

data_io: abnpz

test_data: /home/zhutian/Git_repo/carbonmatrix/pred/g6/npz

test_name_idx: /home/zhutian/Git_repo/carbonmatrix/pred/g6/g6.idx

output_dir: /home/zhutian/Git_repo/carbonmatrix/pred/g6/imfold_g6

verbose: 1
