defaults:
  - model: immunefold
  - transforms: immunefold_inference

restore_model_ckpt: ./params/immunefold-ab.ckpt
restore_esm2_model: ./params/esm2_t36_3B_UR50D.pt

gpu: 0

batch_size: 1

type: nb 

data_io: fasta

test_data: ./data/nanobody_H.fasta

output_dir: ./pred/nanobody

verbose: 1
