defaults:
  - loss: carbonfold_sde
  - model: carbonfold_diffuser
  - transforms: diffuser.yaml

# device
gpu_list: [0,1,2,3]

# lora
lora:
 enabled: False
 lora_r_seq: 16
 lora_r_pair: 8
 lora_scaling: 1.0

model_align:
  lora: False
  bias: True

# optimizer
num_epoch: 1024
warmup_steps: 0
flat_steps: 100000
decay_steps: 2000
learning_rate: 0.0001

# model
restore_model_ckpt: ../abdata_2023/esm2/carbonfold_from_esmfold.ckpt
restore_esm2_model: ../abdata_2023/esm2/esm2_t36_3B_UR50D.pt

# dataset
batch_size: 2
gradient_accumulation_it: 1
max_seq_len: 288
train_name_idx: ../data/carbonfold/cluster.idx
train_data: ../data/carbonfold/mmCIF_npz
# train_name_idx: ../data_2023/pdb50_v2/clean_bc40_cluster.idx
# train_data: ../data_2023/pdb50_v2/data/
    
# output
output_dir: ./studies/train_diffuser_fft_v2

checkpoint_every_step: 1000

verbose: 1
random_seed: 2023
