defaults:
  - loss: carbonfold
  - model: carbonfold
  - transforms: carbonfold

# device
gpu_list: [3,]

# lora
lora_r_seq: 16
lora_r_pair: 8

# optimizer
num_epoch: 1024
warmup_steps: 0
flat_steps: 40000
decay_steps: 40000
learning_rate: 0.0001

# model
restore_model_ckpt: ../abdata_2023/esm2/carbonfold_from_esmfold.ckpt
restore_esm2_model: ../abdata_2023/esm2/esm2_t36_3B_UR50D.pt
model_features: ./config/data_carbonfold.json
model_config: ./config/model_carbonfold.json
model_align: {}

# dataset
is_ab_feature: True
shuffle_multimer_seq: True
batch_size: 1
gradient_accumulation_it: 1
max_seq_len: 300 
train_name_idx: ../abdata_2023/sabdab/train_cluster.idx 
train_data: ../abdata_2023/sabdab/npz
    
# output
output_dir: ./studies/test0

verbose: 1
random_seed: 2023
